title: Maurice's blog
author:
  name: Maurice Lam
  email: me@mauricelam.com
description: >
  I am a software programmer who likes to write Android apps, Python scripts, and Chrome extensions.
markdown: GFM

minima:
  social_links:
    twitter: mymauricelam
    github:  mauricelam
    stackoverflow: "2921519"
    linkedin: maurice-lam

theme: minima

google_analytics: UA-181508309-3
show_excerpts: true # set to false to remove excerpts on the homepage

plugins:
 - jekyll-feed
 - jekyll-seo-tag
