theme: minima

title: Maurice's blog
author: Maurice Lam
email: me@mauricelam.com
description: > # this means to ignore newlines
  This is Maurice's blog
theme: minima
markdown: GFM

# social links
minima:
  social_links:
    twitter: mymauricelam
    github:  mauricelam
    stackoverflow: "2921519"
    linkedin: maurice-lam

google_analytics: UA-181508309-3
show_excerpts: true # set to false to remove excerpts on the homepage
