title: Maurice's blog
author: Maurice Lam
email: me@mauricelam.com
description: >
  I am a software programmer who likes to write Android apps, Python scripts, and Chrome extensions.
markdown: GFM

twitter_username: mymauricelam
github_username:  mauricelam
stackoverflow_username: "2921519"
linkedin_username: maurice-lam
rss: rss

theme: minima

google_analytics: UA-181508309-3
show_excerpts: true # set to false to remove excerpts on the homepage

plugins:
 - jekyll-feed
 - jekyll-seo-tag
