theme: jekyll-theme-minimal

title: Maurice's blog
author: Maurice Lam
email: me@mauricelam.com
description: > # this means to ignore newlines
  This is Maurice's blog
theme: minima
markdown: GFM

# social links
github_username:  mauricelam
google_analytics: UA-181508309-3

show_excerpts: true # set to false to remove excerpts on the homepage
